### ISSUE TITLE
Progress tracker: LARA - common animations (TLR/AOD)

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/trle-aod_animations#1]
This is the list of all animations that exist both in _TR4: The Last Revelation_ and _TR6: The Angel Of Darkness_. It is extracted from AOD's animation list.
Naturally, checked ones means they have been remade, others are yet to be done.

### Part 1: General animations
- [X] LARA_COMPRESS
- [X] LARA_COMPRESS_TO_JUMPB
- [X] LARA_COMPRESS_TO_JUMPF
- [X] LARA_COMPRESS_TO_JUMPFS
- [X] LARA_COMPRESS_TO_JUMPL
- [X] LARA_COMPRESS_TO_JUMPL_MIRROR
- [X] LARA_COMPRESS_TO_JUMPU
- [X] LARA_COOL_CLIMB
- [X] LARA_DEATH_RUN
- [X] LARA_DEATH_RUN_MIRROR
- [X] LARA_DEATH_STANCE
- [X] LARA_DETH_LAND
- [X] LARA_DIVE
- [X] LARA_DIVE_DEATH
- [X] LARA_DIVE_LAND
- [X] LARA_FALL
- [X] LARA_FAST_FALL
- [X] LARA_FAST_LAND
- [X] LARA_FASTDIVE
- [X] LARA_GRAB
- [X] LARA_HITWALL_A
- [x] LARA_JUMP_SPLAT
- [X] LARA_JUMPB
- [X] LARA_JUMPBSMALL
- [X] LARA_JUMPBSMALL_END
- [X] LARA_JUMPBSMALL_START
- [X] LARA_JUMPF
- [X] LARA_JUMPF_LAND
- [X] LARA_JUMPF_TO_FALLF
- [X] LARA_JUMPF_TO_REACH
- [X] LARA_JUMPL
- [X] LARA_JUMPL_MIRROR
- [X] LARA_JUMPU
- [X] LARA_JUMPU_LAND
- [x] LARA_LEDGE_GRAB
- [X] LARA_REACH
- [X] LARA_REACH_TO_GRAB
- [X] LARA_ROLL
- [X] LARA_ROLL_TO_STANCE
- [X] LARA_RUN
- [X] LARA_RUN_TO_RUNJUMP
- [X] LARA_RUN_TO_RUNJUMP_MIRROR
- [X] LARA_RUN_TO_STANCE
- [X] LARA_RUN_TO_STANCE_MIRROR
- [X] LARA_RUNJUMP
- [X] LARA_RUNJUMP_MIRROR
- [X] LARA_RUNJUMP_TO_RUN
- [X] LARA_RUNSTEPUP_QTR
- [X] LARA_RUNSTEPUP_QTR_MIRROR
- [X] LARA_SHIMMY
- [x] LARA_SHIMMY_CORNER_INSIDE
- [x] LARA_SHIMMY_CORNER_INSIDE_MIRROR
- [ ] LARA_SHIMMY_CORNER_OUTSIDE
- [ ] LARA_SHIMMY_CORNER_OUTSIDE_MIRROR
- [X] LARA_SHIMMY_MIRROR
- [x] LARA_SLIDE_BACK
- [x] LARA_SLIDE_BACK_LAND
- [X] LARA_SLIDE_FORWARD
- [X] LARA_SLIDE_FORWARD_LAND
- [X] LARA_SPRINT
- [X] LARA_STANCE
- [X] LARA_STANCE_TO_ROLL
- [X] LARA_STANCE_TO_RUN
- [X] LARA_STANCE_TO_WALK
- [X] LARA_STANCE_TURN45
- [X] LARA_STANCE_TURN45_MIRROR
- [X] LARA_STANCE_TURN90
- [X] LARA_STANCE_TURN90_END
- [X] LARA_STANCE_TURN90_END_MIRROR
- [X] LARA_STANCE_TURN90_MIRROR
- [X] LARA_STANCE_TURN90_START
- [X] LARA_STANCE_TURN90_START_MIRROR
- [X] LARA_STEP_SIDEB
- [X] LARA_STEP_SIDEB_MIRROR
- [X] LARA_STEPBACK
- [X] LARA_STEPBACK_START
- [X] LARA_STEPBACK_STOP
- [X] LARA_STEPBACK_STOPLEFT
- [X] LARA_STEPUP_HLFBLOCK
- [X] LARA_UP3QTRBLOCK
- [X] LARA_VAULT_A
- [X] LARA_VERTICAL_FALL
- [X] LARA_VERTICAL_LAND
- [X] LARA_WALK
- [X] LARA_WALK_TO_STANCE
- [X] LARA_WALK_TO_STANCE_MIRROR
- [x] LARA_WALKSTEPDOWN_QTR
- [x] LARA_WALKSTEPDOWN_QTR_MIRROR
- [x] LARA_WALKSTEPUP_QTRBLK
- [x] LARA_WALKSTEPUP_QTRBLK_MIRROR
- [X] LARA_WALL_JUMPUP

### Part 2: Water / water surface
- [X] LARA_SURFSWIM
- [X] LARA_SURFSWIM_BACK
- [ ] LARA_SURFSWIM_RIGHT
- [ ] LARA_SURFSWIM_RIGHT_MIRROR
- [X] LARA_SURFTREAD
- [X] LARA_SURFTREAD_TO_LEDGE8TH
- [X] LARA_SURFTREAD_TO_LEDGEQTR
- [X] LARA_SURFTREAD_TO_SWIM
- [X] LARA_SWIM
- [x] LARA_UNDERWATER_DEATH
- [X] LARA_UNDERWATER_TREAD
- [X] LARA_UNDERWATER_TURN180
- [X] LARA_WADE

### Part 3: Crouching / crawling
- [x] LARA_CRAWL_BACK
- [x] LARA_CRAWL_BACK_START
- [x] LARA_CRAWL_BACK_STOP
- [x] LARA_CRAWL_BACK_STOP_MIRROR
- [X] LARA_CRAWL_BREATH
- [x] LARA_CRAWL_DEATH
- [x] LARA_CRAWL_FORWARD
- [x] LARA_CRAWL_FORWARD_START
- [x] LARA_CRAWL_FORWARD_STOP
- [x] LARA_CRAWL_FORWARD_STOP_MIRROR
- [x] LARA_CRAWL_TURN45
- [x] LARA_CRAWL_TURN45_MIRROR
- [X] LARA_CRAWLPOSE_TO_CROUCH
- [X] LARA_CROUCH_BREATH
- [X] LARA_CROUCH_TAKE
- [X] LARA_CROUCH_TO_CRAWLPOSE
- [X] LARA_CROUCH_TO_STANCE
- [X] LARA_CROUCH_TURN45
- [X] LARA_CROUCH_TURN45_RIGHT
- [x] LARA_CROUCHHIT_BACK
- [x] LARA_CROUCHHIT_FRONT
- [ ] LARA_CROUCHHIT_LEFT
- [ ] LARA_CROUCHHIT_RIGHT
- [X] LARA_STANCE_TO_CROUCH
- [ ] LARA VAULT TO CROUCH (does not exist as a file but appears in-game)

### Part 4: Wall climbing
- [ ] LARA_CLIMB_CORNER_INSIDE
- [ ] LARA_CLIMB_CORNER_INSIDE_MIRROR
- [x] LARA_CLIMB_CORNER_OUTSIDE
- [x] LARA_CLIMB_CORNER_OUTSIDE_MIRROR
- [X] LARA_HANG_TO_WALLCLIMBPOSE
- [X] LARA_STANCE_TO_WALLCLIMBPOSE
- [X] LARA_WALLCLIMB_LEFT
- [x] LARA_WALLCLIMB_TO_HANG (actually it's a new one, because she has to go down by a step while she doesn't in AOD)
- [X] LARA_WALLCLIMBDOWN
- [X] LARA_WALLCLIMBDOWN_START
- [X] LARA_WALLCLIMBDOWN_STOP
- [X] LARA_WALLCLIMBDOWN_STOP_MIRROR
- [X] LARA_WALLCLIMBPOSE
- [X] LARA_WALLCLIMBPOSE_ONLEDGE
- [X] LARA_WALLCLIMBSIDE
- [X] LARA_WALLCLIMBUP
- [X] LARA_WALLCLIMBUP_START
- [X] LARA_WALLCLIMBUP_STOP
- [X] LARA_WALLCLIMBUP_STOP_MIRROR
- [X] LARA_WALLCOMPRESS

### Part 5: Monkey swinging
- [x] LARA_MONKEY_FORWARD
- [x] LARA_MONKEY_HANG
- [x] LARA_MONKEY_START
- [x] LARA_MONKEY_STOP
- [x] LARA_MONKEY_STOP_MIRROR
- [ ] LARA_MONKEY_TURN
- [ ] LARA_MONKEY_TURN_MIRROR
- [ ] LARA_MONKEY_TURN_START
- [ ] LARA_MONKEY_TURN_START_MIRROR
- [ ] LARA_MONKEY_TURN_STOP
- [ ] LARA_MONKEY_TURN_STOP_MIRROR

### Part 6: Weapon & inventory objects animations
- [X] LARA_AIM_GUN
- [X] LARA_AIM_GUN_LOOP
- [X] LARA_AIM_LOOP
- [ ] LARA_AIM_SHOTGUN
- [ ] LARA_AIM_SHOTGUN_LOOP
- [X] LARA_DRAW_GUN
- [X] LARA_DRAW_PISTOLS
- [ ] LARA_DRAW_SHOTGUN
- [X] LARA_HOLSTER_GUN
- [X] LARA_HOLSTER_PISTOLS
- [ ] LARA_HOLSTER_SHOTGUN
- [ ] LARA_OPEN_CROWBAR
- [X] LARA_PICK_UP
- [ ] LARA_PICKUP_HIGH
- [x] LARA_PICKUP_MEDIUM
- [ ] LARA_RELOAD_SHOTGUN
- [X] LARA_SHOOT_GUN
- [X] LARA_SHOOT_PISTOLS2
- [ ] LARA_SHOOT_SHOTGUN
- [X] LARA_THROW (used for the flare)
- [ ] LARA_UNDERWATER_PICK
- [x] LARA_USE_KEY
- [X] LARA_USE_OBJECT

### Part 7: Object interaction
- [X] LARA_CHAIN_PULL
- [X] LARA_CHAIN_PULL_END
- [X] LARA_CHAIN_START
- [x] LARA_ESWITCH_DOWN
- [x] LARA_ESWITCH_UP
- [X] LARA_KICK_DOOR_OPEN
- [x] LARA_PULL_BLOCK_HALF
- [x] LARA_PULL_BLOCK_START
- [x] LARA_PULL_BLOCK_STOP
- [x] LARA_PULLDOOR
- [x] LARA_PUSH_BUTTON
- [X] LARA_PUSH_HALFBLOCK
- [X] LARA_PUSH_HALFBLOCK_END
- [X] LARA_PUSH_HALFBLOCK_START
- [x] LARA_PUSH_OBJECT
- [x] LARA_PUSHDOOR
- [X] LARA_PUSHHEAVYDOOR
- [x] LARA_TRAPDOOR_OPEN
- [ ] LARA_TURN_STONE
- [x] LARA_UNDERWATER_LEVER
