### ISSUE TITLE
Progress tracker: LARA - TLR animations

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/trle-aod_animations#2]
This is the list of all animations that only exist in _TR4: The Last Revelation_ and will be remade.
This doesn't count:
- very simple transitions (walk to run, run to stance, swim to tread, etc - they don't need to appear in the list)
- too specific TR4 animations (Seth death, trident placing on statue, etc - they require specific objects and would be used by a handful of builders only)

Naturally, checked ones means they have been remade, others are yet to be done.

### Part 1: General animations
- [ ] Crawl backwards to hang
- [ ] Crawl pickup
- [x] Crawlspace roll
- [x] Dive flip
- [x] Dive to swim (high height)
- [x] Dive to swim (small height)
- [X] Fall death (health loss, not high height)
- [x] Fast fall to swim
- [x] Flare pickup
- [ ] Flare pickup underwater
- [ ] Flare pickup while crouching
- [ ] Hit back
- [ ] Hit front
- [ ] Hit left
- [ ] Hit right
- [X] Jump back to roll in air
- [X] Jump forward to roll in air
- [X] Monkey grab from jump up
- [ ] Monkey shimmy left
- [ ] Monkey shimmy right
- [x] Run to crouch left
- [x] Run to crouch right
- [X] Run to wade left
- [X] Run to wade right
- [X] Slide forward to run
- [x] Sprint skid left
- [x] Sprint skid right
- [ ] Sprint roll left
- [ ] Sprint roll right
- [ ] Sprint roll to crouch left
- [ ] Sprint roll to crouch right
- [X] Stance to sprint
- [X] Stance to wade
- [x] Step back down left
- [x] Step back down right
- [ ] Surface swim death
- [X] Surface swim to wade
- [x] Surface swim to stance (1 click pond)
- [ ] Swim to stance (1 click pond)
- [X] Wade stop left
- [X] Wade stop right
- [X] Wade to run left
- [X] Wade to run right
- [x] Wall climb down with arms only
- [x] Wall climb up with arms only
- [X] Wall climb jump backwards
- [x] Wall climb to hang left
- [x] Wall climb to hang right
- [ ] Zipline grab
- [ ] Zipline
- [ ] Zipline to fall

### Part 2: Polerope
- [x] Jump up to pole stance
- [X] Pole climb up
- [X] Pole jump backwards
- [ ] Pole rotate left
- [ ] Pole rotate right
- [x] Pole slide
- [x] Pole slide to pole stance
- [X] Pole stance
- [x] Pole stance to pole slide
- [x] Pole stance to stance
- [X] Pole to fast fall
- [X] Stance to pole
- [x] Reach to pole stance

### Part 3: Rope
- [ ] Jump up to rope stance
- [ ] Reach to rope stance
- [ ] Rope climb up
- [ ] Rope rotate left
- [ ] Rope rotate right
- [ ] Rope slide
- [ ] Rope slide to rope stance
- [ ] Rope stance
- [ ] Rope stance to rope slide
- [ ] Rope stance to rope swing
- [ ] Rope swing
- [ ] Rope swing to reach 1
- [ ] Rope swing to reach 2
- [ ] Rope swing to reach 3
- [ ] Rope swing to reach 4
- [ ] Rope swing to reach 5
- [ ] Rope swing to reach 6

### Part 4: Object interaction
- [ ] Blown up by mine
- [ ] Ceiling trapdoor open
- [ ] Crowbar door open
- [ ] Crowbar pickup from the wall
- [ ] Crowbar switch
- [ ] Empty waterskin on scales puzzle
- [ ] Empty waterskin on the floor
- [ ] Fill waterskin
- [x] Jump switch
- [x] Lever switch
- [x] Light torch with flame 0 clicks high
- [x] Light torch with flame 1 clicks high
- [x] Light torch with flame 2 clicks high
- [x] Light torch with flame 3 clicks high
- [x] Light torch with flame 4 clicks high (unused in-game)
- [ ] Look through binoculars
- [x] Pickup from sarcophagus
- [ ] Push wall button
- [ ] Rolling ball death
- [x] Throw torch
- [ ] Spike death
- [ ] Underwater ceiling switch
- [ ] Underwater door open
- [ ] Use mine detonator
- [X] Wall switch down
- [x] Wall switch up
- [x] Wall hole pickup/switch
- [ ] Wheel switch
