### ISSUE TITLE
 Progress tracker: LARA - other AOD animations

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/trle-aod_animations#3]
This is the list of all animations that exist in *TR6: The Angel of Darkness* or in other classic Tomb Raider Games (but not in *TR4: The Last Revelation*) that I think I will do as well.
This doesn't count:
- very simple transitions
- gameplay elements that are too complex to script

Naturally, checked ones means they have been remade, others are yet to be done.

### Part 1: TR6 animations that exist in other classics (TR1-2-3-5)
- [ ] LARA_AIM_MACHINEGUN
- [X] LARA_CRAWL_INTO_FALL
- [ ] LARA_DEEP_GRAB
- [ ] LARA_DRAW_MACHINEGUN
- [ ] LARA_DRAWER_*
- [ ] LARA_HARPOON_DRAW (does not appear in-game)
- [ ] LARA_HARPOON_HOLSTER (does not appear in-game)
- [ ] LARA_HARPOON_SHOOT (does not appear in-game)
- [ ] LARA_RELOAD_MACHINEGUN
- [ ] LARA_SHOOT_MACHINEGUN
- [x] LARA_TURN_AIRLOCK
- [ ] LARA_WARDROBE_*
- [ ] LARA_SWIPE_SWITCH

### Part 2: TR6 exclusive - General animations
- [X] LARA_BIGHIT_FRONT
- [X] LARA_JUMPFS
- [X] LARA_JUMPFS_END
- [x] LARA_CROUCH_LEDGEOFF_FRONT (does not exist, but made it anyway, using LARA_LEDGEOFF_FRONT)
- [x] LARA_LEDGEOFF_BACK
- [x] LARA_LEDGEOFF_FRONT
- [ ] LARA_MONKEY_HANG_REVERSE
- [ ] LARA_MONKEY_TO_FREECLIMBUP
- [X] LARA_SKIP_BACK
- [X] LARA_SKIP_BACK_START
- [X] LARA_SKIP_BACK_STOP
- [x] LARA_SKIP_BACK_STOP_EARLY (does not exist but needed for responsiveness)
- [x] LARA_SPRINTJUMP
- [x] LARA_SPRINTJUMP to LARA_REACH transitions (x4)
- [x] LARA_SPRINTJUMP_MIRROR
- [x] LARA_SPRINTJUMP_MIRROR to LARA_REACH transitions (x4)
- [x] LARA_SPRINTJUMP_START
- [x] LARA_SPRINTJUMP_START_MIRROR
- [X] LARA_STANCE_TURN180
- [ ] LARA_SWIM_TO_WALLCLIMB
- [X] LARA_VERTICAL_LAND_SMALL
- [ ] LARA_WAKE_UP

### Part 3: TR6 exclusive - Ladders
- [x] LARA_LADDER_DOWN
- [x] LARA_LADDER_DOWN_START
- [x] LARA_LADDER_DOWN_STOP
- [x] LARA_LADDER_DOWN_STOP_RIGHT
- [ ] LARA_LADDER_OFFSIDE
- [ ] LARA_LADDER_OFFSIDE_MIRROR
- [ ] LARA_LADDER_OFF_BOTTOM
- [ ] LARA_LADDER_OFF_BOTTOM_MIRROR
- [x] LARA_LADDER_OFF_TOP
- [x] LARA_LADDER_OFF_TOP_MIRROR
- [x] LARA_LADDER_ONBOTTOM
- [ ] LARA_LADDER_ONTOP_BACK
- [x] LARA_LADDER_ONTOP_FRONT
- [ ] LARA_LADDER_ON_SIDE
- [ ] LARA_LADDER_ON_SIDE_MIRROR
- [x] LARA_LADDER_UP
- [x] LARA_LADDER_UP_START
- [x] LARA_LADDER_UP_STOP
- [x] LARA_LADDER_UP_STOP_LEFT
- [ ] LARA_SWIM_LADDER_ON

### Part 4: TR6 exclusive - Diagonal ceiling climbing
- [ ] LARA_FREECLIMBDOWN_TO_MONKEY
- [ ] LARA_FREECLIMBDOWN_TO_MONKEY_MIRROR
- [ ] LARA_FREECLIMB_DOWN
- [X] LARA_FREECLIMB_GRAB (used as Wallclimb to Monkey ceiling for now)
- [ ] LARA_FREECLIMB_GRABWALL
- [ ] LARA_FREECLIMB_HANG
- [ ] LARA_FREECLIMB_HANG_MIRROR
- [ ] LARA_FREECLIMB_START
- [ ] LARA_FREECLIMB_STOP_RIGHT
- [ ] LARA_FREECLIMB_STOP_RIGHT_MIRROR
- [ ] LARA_FREECLIMB_TO_MONKEY180
- [ ] LARA_FREECLIMB_TO_MONKEY180_MIRROR
- [ ] LARA_FREECLIMB_TO_WALLCLIMB
- [ ] LARA_FREECLIMB_TO_WALLCLIMB_MIRROR
- [ ] LARA_FREECLIMB_UP
- [ ] LARA_WALLCLIMB_TO_FREECLIMB

### Part 5: TR6 exclusive - Object interaction
- [ ] LARA_BOX_DROP
- [ ] LARA_BOX_HOLD
- [ ] LARA_BOX_PICKUP
- [ ] LARA_BOX_WALKF
- [ ] LARA_BOX_WALKF_START
- [ ] LARA_BOX_WALKF_STOP
- [ ] LARA_BOX_WALKF_STOP_MIRROR
- [X] LARA_KICKOVERKNIGHT
- [X] LARA_PULLLEVER1
- [x] LARA_PUSHLEVER1
- [X] LARA_UNDERWATER_KICK
