### ISSUE TITLE
Progress tracker: SAS

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/trle-aod_animations#4]
I've decided to remake SAS animations, just because I wanted to work on something else than Lara.
I'm also making additional transitions to try to make him more reactive.

_**Note**: these are made from scratch, not based on nor inspired by any AOD character._

### Part 1: Existing animations
- [X] Walk
- [X] Run
- [ ] Sight shoot
- [ ] Stance to sight aim
- [ ] Walk to walk aim (unused?)
- [X] Run to walk
- [ ] Walk shoot (unused?)
- [ ] Sight aim to stance
- [ ] Walk aim to walk (unused?)
- [X] Stance to run
- [ ] Stance to wait
- [X] Stance to walk
- [X] Stance
- [ ] Wait to stance
- [ ] Wait
- [ ] Wait to sight aim
- [x] Walk to run
- [ ] Walk to stance
- [ ] Walk aim to walk
- [ ] Death
- [ ] Stance to hold aim
- [ ] Hold shoot
- [ ] Hold aim to stance
- [ ] Hold prepare grenade
- [ ] Hold shoot grenade
- [ ] Stance to kneel aim
- [ ] Kneel shoot
- [ ] Kneel aim to stance
- [ ] Blind
- [ ] Blind to stance

### Part 2: Additional transitions
These are transitions I can add based on what the engine natively allows.
- [ ] Sight aim to walk [implemented]
- [ ] Sight aim to hold aim [implemented]
- [ ] Sight aim to kneel aim [implemented]
- [ ] Hold aim to walk [implemented]
- [ ] Hold aim to run [implemented]
- [ ] Kneel aim to walk [implemented]
- [ ] Kneel aim to run [implemented]
- [ ] Walk to sight aim 1 [implemented]
- [ ] Walk to sight aim 2 [implemented]
- [ ] Walk to hold aim 1 [implemented]
- [ ] Walk to hold aim 2 [implemented]
- [ ] Walk to kneel aim 1
- [ ] Walk to kneel aim 2
- [ ] Walk to stance 2 [implemented]
- [ ] Walk to run 2
- [ ] Stance to walk cancel [implemented]
